nome = input("Nome: ")
empresa = input("Empresa: ")
qtde_funcionarios =int(input("Quantidade de funcionários: "))
mediaMensalidade = float(input("Mensalidade: "))
print(nome + " trabalha na empresa "+ empresa)
print("Possui: ", qtde_funcionarios, "funcionarios.")
print("A mensalidade é de: " + str(mediaMensalidade))
print("--------------------TIPOS DE DADOS-------------------------")
print("Tipo da variavel [nome]: ", type(nome))
print("Tipo da variavel [empresa]: ", type(empresa))
print("Tipo da variavel [qtde_funcionarios]: ", type(qtde_funcionarios))
print("Tipo da variavel [mediaMensalidade]: ", type(mediaMensalidade))