nome = input("Nome: ")
nomef = input("Nome funcionario: ")
evento = input("Evento: ")
valor = float(input("Valor do evento: "))
print("Declaro para o senhor " + nome + " que o senhor " + nomef + " esteve no evento " + evento + " e gastou o valor de R$" + str(valor)+" com a entrada.") 